/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FlocksRouteImport } from './routes/flocks'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FarmsRouteImport } from './routes/farms'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CooperatorsRouteImport } from './routes/cooperators'
import { Route as CompostRouteImport } from './routes/compost'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FlocksRoute = FlocksRouteImport.update({
  id: '/flocks',
  path: '/flocks',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsRoute = FarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperatorsRoute = CooperatorsRouteImport.update({
  id: '/cooperators',
  path: '/cooperators',
  getParentRoute: () => rootRouteImport,
} as any)
const CompostRoute = CompostRouteImport.update({
  id: '/compost',
  path: '/compost',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compost': typeof CompostRoute
  '/cooperators': typeof CooperatorsRoute
  '/dashboard': typeof DashboardRoute
  '/farms': typeof FarmsRoute
  '/finance': typeof FinanceRoute
  '/flocks': typeof FlocksRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compost': typeof CompostRoute
  '/cooperators': typeof CooperatorsRoute
  '/dashboard': typeof DashboardRoute
  '/farms': typeof FarmsRoute
  '/finance': typeof FinanceRoute
  '/flocks': typeof FlocksRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compost': typeof CompostRoute
  '/cooperators': typeof CooperatorsRoute
  '/dashboard': typeof DashboardRoute
  '/farms': typeof FarmsRoute
  '/finance': typeof FinanceRoute
  '/flocks': typeof FlocksRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compost'
    | '/cooperators'
    | '/dashboard'
    | '/farms'
    | '/finance'
    | '/flocks'
    | '/health'
    | '/login'
    | '/market'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compost'
    | '/cooperators'
    | '/dashboard'
    | '/farms'
    | '/finance'
    | '/flocks'
    | '/health'
    | '/login'
    | '/market'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/compost'
    | '/cooperators'
    | '/dashboard'
    | '/farms'
    | '/finance'
    | '/flocks'
    | '/health'
    | '/login'
    | '/market'
    | '/reports'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompostRoute: typeof CompostRoute
  CooperatorsRoute: typeof CooperatorsRoute
  DashboardRoute: typeof DashboardRoute
  FarmsRoute: typeof FarmsRoute
  FinanceRoute: typeof FinanceRoute
  FlocksRoute: typeof FlocksRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flocks': {
      id: '/flocks'
      path: '/flocks'
      fullPath: '/flocks'
      preLoaderRoute: typeof FlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms': {
      id: '/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof FarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperators': {
      id: '/cooperators'
      path: '/cooperators'
      fullPath: '/cooperators'
      preLoaderRoute: typeof CooperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compost': {
      id: '/compost'
      path: '/compost'
      fullPath: '/compost'
      preLoaderRoute: typeof CompostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompostRoute: CompostRoute,
  CooperatorsRoute: CooperatorsRoute,
  DashboardRoute: DashboardRoute,
  FarmsRoute: FarmsRoute,
  FinanceRoute: FinanceRoute,
  FlocksRoute: FlocksRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
