/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminVentesRouteImport } from './routes/admin/ventes'
import { Route as AdminUtilisateursRouteImport } from './routes/admin/utilisateurs'
import { Route as AdminSortiesRouteImport } from './routes/admin/sorties'
import { Route as AdminRapportsRouteImport } from './routes/admin/rapports'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as AdminNouvelleVenteRouteImport } from './routes/admin/nouvelle-vente'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMedicamentsRouteImport } from './routes/admin/medicaments'
import { Route as AdminImmobilesRouteImport } from './routes/admin/immobiles'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAlertesRouteImport } from './routes/admin/alertes'
import { Route as AdminActiviteRouteImport } from './routes/admin/activite'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVentesRoute = AdminVentesRouteImport.update({
  id: '/admin/ventes',
  path: '/admin/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/admin/utilisateurs',
  path: '/admin/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSortiesRoute = AdminSortiesRouteImport.update({
  id: '/admin/sorties',
  path: '/admin/sorties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRapportsRoute = AdminRapportsRouteImport.update({
  id: '/admin/rapports',
  path: '/admin/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/admin/parametres',
  path: '/admin/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNouvelleVenteRoute = AdminNouvelleVenteRouteImport.update({
  id: '/admin/nouvelle-vente',
  path: '/admin/nouvelle-vente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMedicamentsRoute = AdminMedicamentsRouteImport.update({
  id: '/admin/medicaments',
  path: '/admin/medicaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImmobilesRoute = AdminImmobilesRouteImport.update({
  id: '/admin/immobiles',
  path: '/admin/immobiles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertesRoute = AdminAlertesRouteImport.update({
  id: '/admin/alertes',
  path: '/admin/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActiviteRoute = AdminActiviteRouteImport.update({
  id: '/admin/activite',
  path: '/admin/activite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/activite': typeof AdminActiviteRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/immobiles': typeof AdminImmobilesRoute
  '/admin/medicaments': typeof AdminMedicamentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/nouvelle-vente': typeof AdminNouvelleVenteRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/sorties': typeof AdminSortiesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/ventes': typeof AdminVentesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/activite': typeof AdminActiviteRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/immobiles': typeof AdminImmobilesRoute
  '/admin/medicaments': typeof AdminMedicamentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/nouvelle-vente': typeof AdminNouvelleVenteRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/sorties': typeof AdminSortiesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/ventes': typeof AdminVentesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/activite': typeof AdminActiviteRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/immobiles': typeof AdminImmobilesRoute
  '/admin/medicaments': typeof AdminMedicamentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/nouvelle-vente': typeof AdminNouvelleVenteRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/sorties': typeof AdminSortiesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/ventes': typeof AdminVentesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/activite'
    | '/admin/alertes'
    | '/admin/categories'
    | '/admin/immobiles'
    | '/admin/medicaments'
    | '/admin/notifications'
    | '/admin/nouvelle-vente'
    | '/admin/parametres'
    | '/admin/rapports'
    | '/admin/sorties'
    | '/admin/utilisateurs'
    | '/admin/ventes'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/activite'
    | '/admin/alertes'
    | '/admin/categories'
    | '/admin/immobiles'
    | '/admin/medicaments'
    | '/admin/notifications'
    | '/admin/nouvelle-vente'
    | '/admin/parametres'
    | '/admin/rapports'
    | '/admin/sorties'
    | '/admin/utilisateurs'
    | '/admin/ventes'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/activite'
    | '/admin/alertes'
    | '/admin/categories'
    | '/admin/immobiles'
    | '/admin/medicaments'
    | '/admin/notifications'
    | '/admin/nouvelle-vente'
    | '/admin/parametres'
    | '/admin/rapports'
    | '/admin/sorties'
    | '/admin/utilisateurs'
    | '/admin/ventes'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminActiviteRoute: typeof AdminActiviteRoute
  AdminAlertesRoute: typeof AdminAlertesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminImmobilesRoute: typeof AdminImmobilesRoute
  AdminMedicamentsRoute: typeof AdminMedicamentsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminNouvelleVenteRoute: typeof AdminNouvelleVenteRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminRapportsRoute: typeof AdminRapportsRoute
  AdminSortiesRoute: typeof AdminSortiesRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminVentesRoute: typeof AdminVentesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ventes': {
      id: '/admin/ventes'
      path: '/admin/ventes'
      fullPath: '/admin/ventes'
      preLoaderRoute: typeof AdminVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sorties': {
      id: '/admin/sorties'
      path: '/admin/sorties'
      fullPath: '/admin/sorties'
      preLoaderRoute: typeof AdminSortiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rapports': {
      id: '/admin/rapports'
      path: '/admin/rapports'
      fullPath: '/admin/rapports'
      preLoaderRoute: typeof AdminRapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nouvelle-vente': {
      id: '/admin/nouvelle-vente'
      path: '/admin/nouvelle-vente'
      fullPath: '/admin/nouvelle-vente'
      preLoaderRoute: typeof AdminNouvelleVenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/medicaments': {
      id: '/admin/medicaments'
      path: '/admin/medicaments'
      fullPath: '/admin/medicaments'
      preLoaderRoute: typeof AdminMedicamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/immobiles': {
      id: '/admin/immobiles'
      path: '/admin/immobiles'
      fullPath: '/admin/immobiles'
      preLoaderRoute: typeof AdminImmobilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alertes': {
      id: '/admin/alertes'
      path: '/admin/alertes'
      fullPath: '/admin/alertes'
      preLoaderRoute: typeof AdminAlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activite': {
      id: '/admin/activite'
      path: '/admin/activite'
      fullPath: '/admin/activite'
      preLoaderRoute: typeof AdminActiviteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminActiviteRoute: AdminActiviteRoute,
  AdminAlertesRoute: AdminAlertesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminImmobilesRoute: AdminImmobilesRoute,
  AdminMedicamentsRoute: AdminMedicamentsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminNouvelleVenteRoute: AdminNouvelleVenteRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminRapportsRoute: AdminRapportsRoute,
  AdminSortiesRoute: AdminSortiesRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminVentesRoute: AdminVentesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
