/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientIndexRouteImport } from './routes/_client.index'
import { Route as ProviderSettingsRouteImport } from './routes/provider.settings'
import { Route as ProviderServicesRouteImport } from './routes/provider.services'
import { Route as ProviderReviewsRouteImport } from './routes/provider.reviews'
import { Route as ProviderProfileRouteImport } from './routes/provider.profile'
import { Route as ProviderMessagesRouteImport } from './routes/provider.messages'
import { Route as ProviderBookingsRouteImport } from './routes/provider.bookings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as ClientSearchRouteImport } from './routes/_client.search'
import { Route as ClientProfileRouteImport } from './routes/_client.profile'
import { Route as ClientMessagesRouteImport } from './routes/_client.messages'
import { Route as ClientDashboardRouteImport } from './routes/_client.dashboard'
import { Route as ClientBookingsRouteImport } from './routes/_client.bookings'
import { Route as ClientProvidersIdRouteImport } from './routes/_client.providers.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ProviderSettingsRoute = ProviderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderServicesRoute = ProviderServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderReviewsRoute = ProviderReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderProfileRoute = ProviderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderMessagesRoute = ProviderMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderBookingsRoute = ProviderBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ProviderRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const ClientSearchRoute = ClientSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProvidersIdRoute = ClientProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ClientIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRouteWithChildren
  '/register': typeof RegisterRoute
  '/bookings': typeof ClientBookingsRoute
  '/dashboard': typeof ClientDashboardRoute
  '/messages': typeof ClientMessagesRoute
  '/profile': typeof ClientProfileRoute
  '/search': typeof ClientSearchRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/messages': typeof ProviderMessagesRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/reviews': typeof ProviderReviewsRoute
  '/provider/services': typeof ProviderServicesRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/providers/$id': typeof ClientProvidersIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bookings': typeof ClientBookingsRoute
  '/dashboard': typeof ClientDashboardRoute
  '/messages': typeof ClientMessagesRoute
  '/profile': typeof ClientProfileRoute
  '/search': typeof ClientSearchRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/messages': typeof ProviderMessagesRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/reviews': typeof ProviderReviewsRoute
  '/provider/services': typeof ProviderServicesRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/': typeof ClientIndexRoute
  '/admin': typeof AdminIndexRoute
  '/provider': typeof ProviderIndexRoute
  '/providers/$id': typeof ClientProvidersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_client': typeof ClientRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRouteWithChildren
  '/register': typeof RegisterRoute
  '/_client/bookings': typeof ClientBookingsRoute
  '/_client/dashboard': typeof ClientDashboardRoute
  '/_client/messages': typeof ClientMessagesRoute
  '/_client/profile': typeof ClientProfileRoute
  '/_client/search': typeof ClientSearchRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/messages': typeof ProviderMessagesRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/reviews': typeof ProviderReviewsRoute
  '/provider/services': typeof ProviderServicesRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/_client/': typeof ClientIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/_client/providers/$id': typeof ClientProvidersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/provider'
    | '/register'
    | '/bookings'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/search'
    | '/admin/disputes'
    | '/admin/providers'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/provider/bookings'
    | '/provider/messages'
    | '/provider/profile'
    | '/provider/reviews'
    | '/provider/services'
    | '/provider/settings'
    | '/admin/'
    | '/provider/'
    | '/providers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/bookings'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/search'
    | '/admin/disputes'
    | '/admin/providers'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/provider/bookings'
    | '/provider/messages'
    | '/provider/profile'
    | '/provider/reviews'
    | '/provider/services'
    | '/provider/settings'
    | '/'
    | '/admin'
    | '/provider'
    | '/providers/$id'
  id:
    | '__root__'
    | '/_client'
    | '/admin'
    | '/login'
    | '/provider'
    | '/register'
    | '/_client/bookings'
    | '/_client/dashboard'
    | '/_client/messages'
    | '/_client/profile'
    | '/_client/search'
    | '/admin/disputes'
    | '/admin/providers'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/provider/bookings'
    | '/provider/messages'
    | '/provider/profile'
    | '/provider/reviews'
    | '/provider/services'
    | '/provider/settings'
    | '/_client/'
    | '/admin/'
    | '/provider/'
    | '/_client/providers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClientRoute: typeof ClientRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_client/': {
      id: '/_client/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/provider/settings': {
      id: '/provider/settings'
      path: '/settings'
      fullPath: '/provider/settings'
      preLoaderRoute: typeof ProviderSettingsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/services': {
      id: '/provider/services'
      path: '/services'
      fullPath: '/provider/services'
      preLoaderRoute: typeof ProviderServicesRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/reviews': {
      id: '/provider/reviews'
      path: '/reviews'
      fullPath: '/provider/reviews'
      preLoaderRoute: typeof ProviderReviewsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/profile': {
      id: '/provider/profile'
      path: '/profile'
      fullPath: '/provider/profile'
      preLoaderRoute: typeof ProviderProfileRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/messages': {
      id: '/provider/messages'
      path: '/messages'
      fullPath: '/provider/messages'
      preLoaderRoute: typeof ProviderMessagesRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/bookings': {
      id: '/provider/bookings'
      path: '/bookings'
      fullPath: '/provider/bookings'
      preLoaderRoute: typeof ProviderBookingsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_client/search': {
      id: '/_client/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ClientSearchRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/profile': {
      id: '/_client/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/messages': {
      id: '/_client/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/dashboard': {
      id: '/_client/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/bookings': {
      id: '/_client/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/providers/$id': {
      id: '/_client/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ClientProvidersIdRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientSearchRoute: typeof ClientSearchRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientProvidersIdRoute: typeof ClientProvidersIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookingsRoute: ClientBookingsRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientSearchRoute: ClientSearchRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientProvidersIdRoute: ClientProvidersIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface AdminRouteChildren {
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDisputesRoute: AdminDisputesRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProviderRouteChildren {
  ProviderBookingsRoute: typeof ProviderBookingsRoute
  ProviderMessagesRoute: typeof ProviderMessagesRoute
  ProviderProfileRoute: typeof ProviderProfileRoute
  ProviderReviewsRoute: typeof ProviderReviewsRoute
  ProviderServicesRoute: typeof ProviderServicesRoute
  ProviderSettingsRoute: typeof ProviderSettingsRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderBookingsRoute: ProviderBookingsRoute,
  ProviderMessagesRoute: ProviderMessagesRoute,
  ProviderProfileRoute: ProviderProfileRoute,
  ProviderReviewsRoute: ProviderReviewsRoute,
  ProviderServicesRoute: ProviderServicesRoute,
  ProviderSettingsRoute: ProviderSettingsRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ClientRoute: ClientRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ProviderRoute: ProviderRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
